name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/test.yml

  build:
    needs: test
    if: github.event_name == 'push'
    uses: ./.github/workflows/build.yml
    permissions:
      contents: read
      packages: write
